name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format_lint_test:
    name: Check formatting and lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Check formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint
